### ISSUE TITLE
大神，能不能写的详细一点啊？

### ISSUE THREAD

**Issue by wangyu1823** [farlandliu/majove_efi#1]

**Comment by farlandliu** [comment]
你卡在哪里啦？

**Comment by wangyu1823** [comment]
显卡按照你的config安装完成了。声卡用这个config需要添加一个补丁。用双屏的时候开机时没有输入账户密码的窗口，而用单屏进入系统没有办法使用双屏。还有电池还没有弄。

**Comment by farlandliu** [comment]
这款笔记本不值得折腾。我用这个作备机，能用就行啦。
我的双屏也不太好，要先接上外显，再启动后是正常的。
电池要修改DSDT，[参考](https://blog.csdn.net/wangmj518/article/details/50748681)。
我的有电量显示了，但是切换外接电源后显示又不正常。如果需要，在这里 https://github.com/farlandliu/dsdt

**Comment by wangyu1823** [comment]
非常感谢。我也不折腾了。
